namespaceToAllowEgress:
  - dynatrace

ipBlockToAllowEgress: []

serviceAccount:
  create: false
  automount: true
  name: "default"

service:
  type: ClusterIP
  port: 8000

imagePullSecrets: []

image:
  pullPolicy: Never
  tag: "latest"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Environment-specific configuration
environment:
  watchNamespace: dsa-re-dev

# RBAC configuration
rbac:
  create: true
  clusterRoleName: "dsa-pod-patch"  # Reuse existing ClusterRole