kind: pipeline
type: kubernetes
name: build-test

platform:
  os: linux
  arch: amd64
  
workspace:
  path: /backend/registration-service

steps:
# Build the image from the docker file
- name: build
  image: docker
  commands:
  - docker build -t quay.io/ukhomeofficedigital/dsa-re-registration-service:latest .

# Push the docker image to quay.io repo
- name: publish
  image: docker
  commands:
  - docker push quay.io/ukhomeofficedigital/dsa-re-registration-service:latest

trigger:
  event:
  - push


