kind: pipeline
type: docker
name: build-test

platform:
  os: linux
  arch: amd64

steps:
# Build the image from the docker file
- name: build
  image: docker
  commands:
  - docker build -t quay.io/ukhomeofficedigital/dsa-re-registration-service:latest .

# Push the docker image to quay.io repo
- name: publish
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dsa-re-registration-service


