apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: dsa-re-devS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: test-app
        image: quay.io/prometheus/busybox
