kind: pipeline
type: kubernetes
name: build-test

platform:
  os: linux
  arch: amd64

# steps:
# # Build the image from the docker file
# - name: build
#   image: docker
#   commands:
#   - docker build -t quay.io/ukhomeofficedigital/dsa-re-registration-service:latest .

# # Push the docker image to quay.io repo
# - name: publish
#   image: docker
#   commands:
#   - docker push quay.io/ukhomeofficedigital/dsa-re-registration-service:latest

steps:
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: backend/registration-service/Dockerfile
      registry: quay.io
      context: backend/registration-service
      repo: quay.io/ukhomeofficedigital/dsa-re-registration-service
      tags:
      - latest
      username:
        from_secret: QUAY_USERNAME
      password:
        from_secret: QUAY_PASSWORD

trigger:
  event:
  - push


