kind: pipeline
type: kubernetes
name: build-test

platform:
  os: linux
  arch: amd64

steps:

  - name: debug-versions
    image: quay.io/ukhomeofficedigital/helm:3.15.4-build.1
    commands:
      - kubectl config set-cluster buildstep --server=$SHOWCASE_KUBE_SERVER
      - kubectl config set-credentials $SHOWCASE_KUBE_USER --token=$SHOWCASE_KUBE_TOKEN
      - kubectl config set-context buildstep --cluster=buildstep --user=$SHOWCASE_KUBE_USER --namespace=$SHOWCASE_KUBE_NAMESPACE
      - kubectl config use-context buildstep
      - helm version
      - kubectl version
      - kubectl get pods
    environment:
      SHOWCASE_KUBE_USER:
        from_secret: KUBE_NAMESPACE_DEV
      SHOWCASE_KUBE_NAMESPACE:
        from_secret: KUBE_NAMESPACE_DEV
      SHOWCASE_KUBE_SERVER:
        from_secret: KUBE_SERVER_NOT_PROD
      SHOWCASE_KUBE_TOKEN:
        from_secret: KUBE_TOKEN_DEV

  - name: helm-test
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version

  - name: helm-install
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version

trigger:
  event:
  - push
