kind: pipeline
type: kubernetes
name: build-test

platform:
  os: linux
  arch: amd64

steps:

  # - name: docker
  #   image: plugins/docker
  #   settings:
  #     dockerfile: backend/registration-service/Dockerfile
  #     registry: quay.io
  #     context: backend/registration-service
  #     tags:
  #     - latest
  #     repo: quay.io/ukhomeofficedigital/dsa-re-registration-service
  #     username:
  #       from_secret: ROBOT_QUAY_USER
  #     password:
  #       from_secret: ROBOT_QUAY_PASS

  - name: helm-package
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - pwd
      - ls
      - kubectl config set-cluster $KUBE_CLUSTER_NAME --server=$KUBE_SERVER
      - kubectl config set clusters.$KUBE_CLUSTER_NAME.certificate-authority-data $KUBE_CERTIFICATE_AUTHORITY_DATA
      - kubectl config set-credentials helm --token=$KUBE_TOKEN
      - kubectl config set-context $KUBE_CLUSTER_NAME --cluster=$KUBE_CLUSTER_NAME --user=helm
      - kubectl config use-context $KUBE_CLUSTER_NAME
      - kubectl version
    environment:
      KUBE_NAMESPACE:
        from_secret: KUBE_NAMESPACE_DEV
      KUBE_SERVER:
        from_secret: KUBE_SERVER_NOTPROD
      KUBE_TOKEN:
        from_secret: KUBE_TOKEN_DEV
      KUBE_CERTIFICATE_AUTHORITY_DATA:
        from_secret: KUBE_CERTIFICATE_AUTHORITY_DATA_NOTPROD
      KUBE_CLUSTER_NAME:
        from_secret: KUBE_CLUSTER_NAME_NOTPROD


trigger:
  event:
  - push

  # - name: debug-versions
  #   image: quay.io/ukhomeofficedigital/helm:3.15.4-build.1
  #   commands:
  #     - kubectl config set-cluster buildstep --server=$SHOWCASE_KUBE_SERVER
  #     - kubectl config set-credentials $SHOWCASE_KUBE_USER --token=$SHOWCASE_KUBE_TOKEN
  #     - kubectl config set-context buildstep --cluster=buildstep --user=$SHOWCASE_KUBE_USER --namespace=$SHOWCASE_KUBE_NAMESPACE
  #     - kubectl config use-context buildstep
  #     - helm version
  #     - kubectl --context=buildstep version
  #     - helm list --kube-context=buildstep
  #     - helm list --namespace=$SHOWCASE_KUBE_NAMESPACE --kube-apiserver=$SHOWCASE_KUBE_SERVER --kube-token=$SHOWCASE_KUBE_TOKEN
  #   environment:
  #     SHOWCASE_KUBE_USER:
  #       from_secret: KUBE_NAMESPACE_DEV
  #     SHOWCASE_KUBE_NAMESPACE:
  #       from_secret: KUBE_NAMESPACE_DEV
  #     SHOWCASE_KUBE_SERVER:
  #       from_secret: KUBE_SERVER_NOT_PROD
  #     SHOWCASE_KUBE_TOKEN:
  #       from_secret: KUBE_TOKEN_DEV

  # - name: helm-test
  #   image: quay.io/ukhomeofficedigital/helm:v3.5.4
  #   commands:
  #     - helm version
  #     - kubectl version

  # - name: helm-install
  #   image: quay.io/ukhomeofficedigital/helm:v3.5.4
  #   commands:
  #     - helm version
  #     - kubectl version

