kind: pipeline
type: kubernetes
name: build-test

platform:
  os: linux
  arch: amd64

steps:

  - name: debug-versions
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - kubectl config set-cluster buildstep --server=$KUBE_SERVER
      - kubectl config set-credentials $KUBE_USER --token=$KUBE_TOKEN
      - kubectl config set-context buildstep --cluster=buildstep --user=$KUBE_USER --namespace=$KUBE_NAMESPACE
      - kubectl config use-context buildstep
      - helm version
      - kubectl version
      - helm list
    environment:
      KUBE_USER:
        from_secret: KUBE_NAMESPACE_DEV
      KUBE_NAMESPACE:
        from_secret: KUBE_NAMESPACE_DEV
      KUBE_SERVER:
        from_secret: KUBE_SERVER_NOT_PROD
      KUBE_TOKEN:
        from_secret: KUBE_TOKEN_DEV

  - name: helm-test
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version

  - name: helm-install
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version

trigger:
  event:
  - push
