kind: pipeline
type: kubernetes
name: build-test

platform:
  os: linux
  arch: amd64

steps:

  - name: debug-versions
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version
      - helm list --kube-apiserver=$${FAKE_SECRET} --namespace=$${KUBE_NAMESPACE}
    environment:
      KUBE_NAMESPACE:
        from_secret: KUBE_NAMESPACE_DEV
      KUBE_SERVER:
        from_secret: KUBE_SERVER_NOT_PROD
      KUBE_TOKEN:
        from_secret: KUBE_TOKEN_DEV
      FAKE_SECRET:
        from_secret: FAKE_SECRET

  - name: helm-test
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version

  - name: helm-install
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    commands:
      - helm version
      - kubectl version

trigger:
  event:
  - push
