apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-login-preprod
  namespace: dsa-re-preprod
spec:
  schedule: "*/10 * * * *"
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          containers:
          - name: trigger-login
            image: "quay.io/ukhomeofficedigital/dsa-re-msk-cron:latest"
            imagePullPolicy: Always
            env:
            - name: REGISTRATION_SERVICE_URL
              value: "http://registration-service.dsa-re-preprod.svc.cluster.local"
          restartPolicy: OnFailure