apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trigger-login
  namespace: dsa-re-dev
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger-login
            image: "quay.io/ukhomeofficedigital/dsa-re-msk-cron:latest"
            imagePullPolicy: Always
          restartPolicy: OnFailure
