apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "registration-service.fullname" . }}
  labels:
    {{- include "registration-service.labels" . | nindent 4 }}
spec:
  egress:
    - to:
      {{- range .Values.namespaceToAllowEgress }}
      - namespaceSelector:
          matchLabels:
            name: {{ . }}
      {{- end }}
  podSelector:
    matchLabels:
      {{- include "registration-service.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
