apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride | default (include "oneagent-failure-watcher.fullname" .) }}
  labels:
    app: oneagent-init-failure-watcher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: oneagent-init-failure-watcher
  template:
    metadata:
      labels:
        app: oneagent-init-failure-watcher
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: oneagent-init-failure-watcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NAMESPACE
              value: "dsa-re-preprod"