apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    {{- include "frontend-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "frontend-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "frontend-service.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      {{- if((.Values.dynatrace).podRuntimeInjection).enabled }}
      initContainers:
        - name: install-oneagent
          image: quay.io/ukhomeofficedigital/dsa-re-dynatrace-oneagent-pod-runtime-injection:1.0.0
          env:
            - name: DYNATRACE_API_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-service-dynatrace-oneagent
                  key: api-url
            - name: DYNATRACE_PAAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend-service-dynatrace-oneagent
                  key: paas-installer-download-token
            - name: DYNATRACE_ONEAGENT_OPTIONS
              value: flavor=multidistro&include=nodejs
            - name: DYNATRACE_INSTALL_DIR
              value: /opt/dynatrace/oneagent
          volumeMounts:
            - mountPath: /opt/dynatrace/oneagent
              name: {{ (((.Values).dynatrace).podRuntimeInjection).volumeName | default "oneagent" }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "quay.io/ukhomeofficedigital/dsa-re-frontend-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
              - name: Host
                value: localhost
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
              - name: Host
                value: localhost
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if((.Values.dynatrace).podRuntimeInjection).enabled }}
            - name: LD_PRELOAD
              value: /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so
          {{- end -}}
          {{- if((.Values.dynatrace).podRuntimeInjection).enabled }}
          volumeMounts:
            - name: {{ (((.Values).dynatrace).podRuntimeInjection).volumeName | default "oneagent" }}
              mountPath: /opt/dynatrace/oneagent
          {{- end -}}
      {{- if((.Values.dynatrace).podRuntimeInjection).enabled }}
      volumes:
        - name: {{ (((.Values).dynatrace).podRuntimeInjection).volumeName | default "oneagent" }}
          emptyDir: {}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
