apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    {{- include "frontend-service.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
  egress:
    - to:
      {{- range .Values.namespaceToAllowEgress }}
      - namespaceSelector:
          matchLabels:
            name: {{ . }}
      {{- end }}
      {{- range .Values.ipBlockToAllowEgress }}
      - ipBlock:
          cidr: {{ . }}
     {{- end }}
  podSelector:
    matchLabels:
      {{- include "frontend-service.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
