apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    {{- include "frontend-service.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
      - namespaceSelector:
          matchLabels:
            name: ingress-internal
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
    {{- range .Values.namespaceToAllowEgress }}
    - to:
      - namespaceSelector:
          matchLabels:
            name: {{ . }}
    {{- end }}
    {{- range .Values.ipBlockToAllowEgress }}
    - to:
      - ipBlock:
          cidr: {{ . }}
    {{- end }}
  podSelector:
    matchLabels:
      {{- include "frontend-service.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
