---
serviceAccount:
  name: "dynatrace-oneagent-metadata-viewer"

dynatrace:
  podRuntimeInjection:
    enabled: true
  networkZone: "dsa-preprod-acp-prod-rtg-00"

persistenceCredentialsSecretName: dsaredevshowcase-rds