namespaceToAllowEgress:
  - dynatrace

ipBlockToAllowEgress: []

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "dynatrace-oneagent-metadata-viewer"

service:
  type: ClusterIP
  port: 80

imagePullSecrets: []

dynatrace:
  podRuntimeInjection:
    enabled: true

image:
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# kafka config - preprod MSK cluster
kafka:
  bootstrapServers: "b-1.dsarepreprodshowcase.rfkas2.c2.kafka.eu-west-2.amazonaws.com:9094,b-2.dsarepreprodshowcase.rfkas2.c2.kafka.eu-west-2.amazonaws.com:9094"
  topic: "user-login"
  groupId: "notification-service"
  certPath: "/etc/kafka-certs"

# Preprod-specific configuration
environment: preprod

# OTLP configuration for Dynatrace metrics
otlp:
  endpoint: "https://dynatrace-activegate-preprod.dynatrace-preprod.svc.cluster.local/e/vir21829/api/v2/otlp/v1/metrics"
  tokenSecret:
    name: "registration-service-dynatrace-prod-metrics-ingest"
    key: "token"