namespaceToAllowEgress:
  - dynatrace-preprod

ipBlockToAllowEgress: []

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "dynatrace-oneagent-metadata-viewer"

service:
  type: ClusterIP
  port: 80

imagePullSecrets: []

dynatrace:
  podRuntimeInjection:
    enabled: true

image:
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# kafka config
kafka:
  bootstrapServers: "b-1.dsaredevshowcase.rfkas2.c2.kafka.eu-west-2.amazonaws.com:9094,b-2.dsaredevshowcase.rfkas2.c2.kafka.eu-west-2.amazonaws.com:9094"
  topic: "user-login"
  groupId: "notification-service"
  certPath: "/etc/kafka-certs"
