namespaceToAllowEgress:
  - dynatrace

ipBlockToAllowEgress:
  - 10.250.24.0/21
  - 10.250.96.0/19

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "dynatrace-oneagent-metadata-viewer"

imagePullSecrets: []

dynatrace:
  podRuntimeInjection:
    enabled: false

image:
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

persistenceCredentialsSecretName: dsaredevshowcase-rds
