namespaceToAllowEgress:
  - dynatrace

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "dynatrace-oneagent-metadata-viewer"

imagePullSecrets: []

dynatrace:
  podRuntimeInjection:
    enabled: false

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

persistenceCredentialsSecretName: dsaredevshowcase-rds
